# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gose-test

resources:
- namespace.yaml
- obc.yaml
- ingress.yaml
- service.yaml
- deployment.yaml

secretGenerator:
- name: config
  files:
  - config.yaml

generatorOptions:
  disableNameSuffixHash: true
